log:
  level: debug
  disable_sentry: true

db:
  url: postgres://project:project@localhost:5434/project?sslmode=disable

listener:
  addr: :8090 # TODO configure and rm this TODO

cop:
  disabled: true
  endpoint: "https://localhost"
  service_name: project
  service_port: 8090



